export interface Project {
  summary: string;
  /** The words of `summary` set in bold, wherever they fall — usually the place. */
  bold?: string;
}

export interface Role {
  employer: string;
  title: string;
  location: string;
  dates: string;
  context?: string;
  /**
   * An illustration hung from the rule under the header, in `public/experience`.
   * Drawn as SVG on a 1200 × 1040 board — the frame's own 30:26 — with the
   * subject kept in the top right, the only part the curve and the fade leave
   * whole. Decorative — it restates the bullets beside it, so assistive
   * technology skips it.
   */
  image?: string;
  projects: Project[];
}

export const experience: Role[] = [
  {
    employer: "Modeling Biomedical Systems Course",
    title: "Teaching Assistant",
    location: "Stanford, CA",
    dates: "2026",
    context:
      "At the core of informatics is the problem of creating computable models of biomedical phenomena. This course explores methods for modeling biomedical systems with an emphasis on contemporary semantic technology, including knowledge graphs, and is open only to Clinical Informatics Management M.S. students, who are working professionals in the field. Topics: data modeling, knowledge representation, controlled terminologies, ontologies, reusable problem solvers, and modeling problems in healthcare information technology and other aspects of informatics. Students acquire hands-on experience with several systems and tools.",
    projects: [
      {
        summary: "Write the course's homework assignments.",
      },
      {
        summary: "Grade homework assignments.",
      },
      {
        summary: "Host weekly office hours.",
      },
      {
        summary: "Advise on course content and curriculum.",
      },
      {
        summary: "Lead in-class workshops.",
      },
    ],
  },
  {
    employer: "Inspirit AI",
    title: "Product Manager",
    location: "Palo Alto, CA",
    dates: "2025 — Present",
    context:
      "Inspirit AI Scholars is an artificial intelligence education program for high school students, developed by Stanford and MIT alumni and graduate students.",
    image: "/experience/inspirit-ai.svg",
    projects: [
      {
        summary:
          "Built interactive web applications, Jupyter notebooks, and technical curricula to teach AI concepts",
      },
      {
        summary:
          "Lead technical product operations, directly managing 200+ employees, running performance evaluations, allocating work,  and advising teams on research direction, technical roadblocks, and client escalations.",
      },
      {
        summary:
          "Built python scripts to automate high-volume manual workflows including project matching, creation and archival of project Slack channels, and enrollment of thousands of students across course platforms.",
      },
      {
        summary:
          "Served as an on-call software engineer for urgent software bug fixes.",
      },
    ],
  },
  {
    employer: "Melio",
    title: "Software Engineer Intern",
    location: "Mountain View, CA",
    dates: "2024",
    context:
      "Melio is a biotechnology company that builds rapid, culture-free diagnostic platforms to detect bloodborne pathogens and bloodstream infections. Melio is a Fogarty Innovation portfolio company.",
    image: "/experience/melio.svg",
    projects: [
      {
        summary:
          "Developed an optimization algorithm for PCR primer selection to maximize the differences between melt curves of different pathogens while minimizing the differences of melt curves generated by different strains of the same species.",
      },
      {
        summary:
          "Performed DNA sequence alignment and consensus sequencing across the platform's target pathogen panel to characterize phylogenetic relatedness between species, flagging closely related organisms at elevated risk of misclassification.",
      },
      {
        summary:
          "Worked with the ML team to diagnose patients from the melt-curve profile of a blood sample.",
      },
    ],
  },
  {
    employer: "Immergo Labs",
    title: "Software Engineer Intern",
    location: "Mountain View, CA",
    dates: "2024",
    context:
      "Immergo Labs is an NSF-funded digital health company that builds an extended reality (XR) and AI-powered platform for physical rehabilitation and remote movement care. Immergo Labs is a Fogarty Innovation portfolio company.",
    image: "/experience/immergo-labs.svg",
    projects: [
      {
        summary:
          "Developed immersive virtual environments in Unity for a VR telehealth platform. My goal was to create fun and relaxing environments where the patients feel comfortable and at ease.",
      },
      {
        summary:
          "Turned prescribed rehab movement into guided sessions patients complete inside the headset.",
      },
      {
        summary:
          "Helped organize and run a 20-person user study comprised of physical therapy patients and clinicians from across the United States who tried out our XR app and provided feedback. I subsequently worked with the team to triage the feedback and create a plan for integrating the most urgent changes."
      }
    ],
  },
  {
    employer: "Fogarty Innovation",
    title: "Medical Technology Lefteroff Intern",
    location: "Mountain View, CA",
    dates: "2024",
    context:
      "Fogarty Innovation is an action-oriented nonprofit organization that advances human health by accelerating medtech innovation from concept to clinical impact. Melio and Immergo Labs are Fogarty portfolio companies.",
    image: "/experience/fogarty-innovation.svg",
    projects: [
      {
        summary:
          "Consulted on the biodesign process: how a clinical need is identified and characterized before anyone designs the device that answers it.",
      },
      {
        summary:
          "Learned about regulatory strategy, patents, commercialization of medical technology, and the path a device takes from a working prototype to something a hospital can actually buy.",
      },
    ],
  },
  {
    employer: "Skywalk",
    title: "Software Engineer & Data Science Intern",
    location: "Palo Alto, CA",
    dates: "2023",
    context:
      "Skywalk is a software and deep-technology development company focused on building computing devices and specialized software, such as a voicebuds audio device and assistive wrist-worn devices for interfacing with technology.",
    image: "/experience/skywalk.svg",
    projects: [
      {
        summary:
          "Developed signal-quality algorithms to detect artifact-corrupted channels from wrist-worn optical EMG sensors: benchmarked a root-mean-square successive-difference method, diagnosed its high false-positive rate, and replaced it with a variance-based detector whose threshold is normalized by the ratio of optical signal to power output.",
      },
      {
        summary:
          "Designed and executed a 100-participant user study to generate training data for the company's ML models. As part of the study, I built a Unity application for the Microsoft HoloLens AR environment for participants. Participants completed various tasks in the process of completing games in the AR application, and I collected their EMG data in the process.",
      },
      {
        summary:
          "Authored Python processing pipelines to prepare study data for model training including: automating header labeling, detecting and removing corrupted files, and standardizing the data across participants.",
      },
    ],
  },
  {
    employer: "Needs Finding in Healthcare Course",
    title: "Teaching Assistant",
    location: "Stanford, CA",
    dates: "2023",
    context:
      "Needs Finding in Healthcare is a Sophomore College (SoCo) experiential course offered through Stanford Biodesign that teaches undergraduates how to identify unmet medical problems through direct clinical observation. Students shadow in the hospital, identify unmet clinical needs, and apply the biodesign process to those needs.",
    projects: [
      {
        summary:
          "Helped plan the course curriculum, including choosing and organizing educational field trips.",
      },
      {
        summary: "Held office hours to answer student questions.",
      },
      {
        summary: "Attended class to facilitate class discussions and answer student questions.",
      },
    ],
  },
  {
    employer: "Argo AI",
    title: "Software Engineer Intern",
    location: "Palo Alto, CA",
    dates: "2022",
    context:
      "Argo AI was an autonomous driving technology company backed by Ford, Volkswagen, Lyft, and Walmart. I worked on the System Fault Detection & Management team.",
    image: "/experience/argo-ai.svg",
    projects: [
      {
        summary:
          "Built a Python tool that extracts diagnostic signals from autonomous vehicle logs and renders them as time-series visualizations, with cross-vehicle and cross-signal comparison, time-window filtering, and threshold-based queries. This tools allowed employees to visually see what information all of the car's sensors were receiving at the time of an incident with the car. This replaced a workflow that had previosuly been manual and very tedious.",
      },
      {
        summary:
          "Broadened access to that tooling company-wide by removing the prerequisite of Python scripting expertise, letting non-engineering employees analyze and compare log data across multiple vehicles and trips on their own.",
      },
      {
        summary:
          "Developed a C++ front-end that unified the safety and diagnostics team's fragmented internal tooling into a single entry point: users pose a diagnostic question, and the program routes to the appropriate underlying tool, prompts for any missing parameters, and executes it against their data. This made tools previously known only within the team usable across the organization.",
      },
      {
        summary: "Generated and processed new data for the ML team's fault-detection models.",
      },
    ],
  },
  {
    employer: "",
    title: "Teacher",
    location: "Bay Area, CA",
    dates: "2021 — Present",
    image: "/experience/peninsula-tutoring.svg",
    projects: [
      {
        summary:
          "A Breakout Mentors: Taught students ages 8-12 the fundamentals of computer science and programming/",
        bold: "Breakout Mentors",
      },
      {
        summary:
          "At Peninsula Tutoring: Tutored students ages 8-18 in AP Computer Science, AP Calculus, trigonometry, AP Phyiscs, AP Biology, and AP Chemistry",
        bold: "Peninsula Tutoring",
      },
      {
        summary:
          "At Harker School: Taught an AI course to high school students.",
        bold: "Harker School",
      },
      {
        summary:
          "At Nueva School: Taught an AI course to high school students and an introductory AI course to middle school students.",
        bold: "Nueva School",
      },
      {
        summary:
          "At Phillips Academy Exeter: Taught a generative AI course to high school seniors.",
        bold: "Phillips Academy Exeter",
      },
    ],
  },
];
